name: test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57
          args: --enable-all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: subdir/go.sum
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Test
        run: GOEXPERIMENT=rangefunc go test ./...

      - name: generate test coverage
        run: GOEXPERIMENT=rangefunc go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/org/project
          threshold-file: 80
          threshold-package: 80
          threshold-total: 95

